stages:
  - build
  - test
  - publish

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  dependencies:
    - build
  image: node:latest
  stage: test
  script:
    - npm test

publish:
  dependencies:
    - test
  image: node:latest
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == "release" || $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/
  script:
    # If no .npmrc is included in the repo, generate a temporary one that is configured to publish to GitLab's NPM registry
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
